### ISSUE TITLE
How to build gator in Android Q?

### ISSUE THREAD

**Issue by bylanhao** [ARM-software/gator#18]
How to build gator in Android Q?
I try to build gator in Android Q, linux-4.14.
But the Android Q NDK does not support Makefile to build gatord, and not support gcc.
And when build the gator with linux-4.14 and ddk driver r21, miss some function, and cannot build too.

how can i build gator in Android Q?
Thanks.

**Comment by bengaineyarm** [comment]
You can use the provided helper scripts or the cmake based build to compile with modern NDK ersions
