### ISSUE TITLE
gator 7.2 release?

### ISSUE THREAD

**Issue by thkaw** [ARM-software/gator#19]
Hi,

I couldn't found driver folder which should be
Development Studio 2020.0\sw\streamline\gator\driver

But only daemon...
So I can't build the v7.2 gator.ko for Development Studio 2020.0.
Neither not found v7.2 release in this repository. 

Where can I get the source code that I can build v7.2 gator.ko?

Thanks

**Comment by bengaineyarm** [comment]
Hi

There is no gator.ko any more. It was previously deprecated and now removed. As it stands there are no major use cases that would still require gator.ko which cannot be achieved with just gatord, and several features (such as application profiling) that are not possible with gator.ko.

Was there some specific reason you are using gator.ko?

Regarding this repo, recent global events somewhat distracted the team so we forgot to upload, but I'll have that done shortly.

Regards
Ben
