### ISSUE TITLE
How to get gpu usage and frequency in Android 10+

### ISSUE THREAD

**Issue by ylz-at** [ARM-software/gator#24]
For GPU usage, described in https://developer.arm.com/ip-products/graphics-and-multimedia/mali-gpus/mali-performance-counters/mali-g76-counters

**Comment by bengaineyarm** [comment]
Hi

GPU Activity and Clock frequency requires access to certain data which is only accessible to gator when running as root (so requires an engineering build of Android, or a rooted device). 

Also, not all hardware vendors enable to appropriate settings in the Mali GPU driver / platform integration to output this data, so even if you have a rooted device, you may not see these counters.
