### ISSUE TITLE
License of performance counter XML

### ISSUE THREAD

**Issue by alyssarosenzweig** [ARM-software/gator#25]
gator contains two sources of Mali performance counters: XML files (with human-readable names, descriptions and units) and a single header file (with machine-readable names only). Currently both are currently under gator's GPLv2, which prevents their usage in MIT licensed projects working with Mali performance counters.

A variant of gator's header is available in HWCPipe under HWCPipe's MIT license (https://github.com/ARM-software/HWCPipe/blob/master/vendor/arm/mali/hwc_names.hpp). As a stopgap, this allows MIT licensed projects to access the raw names of the Mali counters, but prevents access to the descriptions/units/etc.

Would it be possible to dual-license gator's XML files as MIT? Our team would like to integrate Mali counters with Google's Perfetto in the context of upstream Mali drivers. I suspect HWCPipe would be improved with the extra information in-tree, as well.

Example XML file: https://github.com/ARM-software/gator/blob/master/daemon/events-Mali-G52_hw.xml

Thank you.

**Comment by bengaineyarm** [comment]
Hi Alyssa,

No worries, please see https://github.com/ARM-software/HWCPipe/tree/master/misc/gator-counter-definitions .

Regards
Ben

**Comment by alyssarosenzweig** [comment]
Thank you!
