### ISSUE TITLE
How to use Streamline to enable PMU

### ISSUE THREAD

**Issue by peyer** [ARM-software/gator#30]
I download and install Streamline software, and connect a Android mobile phone that has a Soc named Hisilicon Kirin980.
However, when I configure Counters, it return a warning like below

No Perf PMUs detected
Could not detect any Perf PMUs in /sys/bus/event_source/devices/ but the system contains recognised CPUs. The system may not support perf hardware counters. Check CONFIG_HW_PERF_EVENTS is set and that the PMU is configured in the target device tree.

How should I solve it? Could you give some advice?

**Comment by forestrf** [comment]
Same problem here. Device is Moto E4 (MTK MT6737 with Mali T720) (the device is rooted).

Same warning as OP:

> No Perf PMUs detected
> Could not detect any Perf PMUs in /sys/bus/event_source/devices/ but the system contains recognised CPUs. The system may not support perf hardware counters. Check CONFIG_HW_PERF_EVENTS is set and that the PMU is configured in the target device tree.

**Comment by bengaineyarm** [comment]
Hi both;

On its own this is a warning and you may be able to still capture CPU performance counters; it largely depends on how the kernel has been configured along with the specific device integration. The only way to know for sure it to attempt to make a capture after configuring some simple counters such as "CPU Cycles" or "Instructions Executed" which should be present and generate events on all CPUs (so long as the PMU is configured correctly).

Unfortunately if it doesn't work, there is usually little you can do, even with a rooted phone, unless you are willing / able to make modifications to the kernel and possibly device tree file.

You should usually still be able to collect GPU counters and Linux software events.
