### ISSUE TITLE
The GPU usage is not shown with streamline v9.4.0. - Mali G78AE

### ISSUE THREAD

**Issue by sooyeon-kang** [ARM-software/gator#54]
I used a custom embedded device using Mali G78AE.
when I ran the streamline v9.4.0, GPU usage is not shown in the streamline.
I think the support for Mali G78AE is missing from gator..

Could you check it?
Thanks.

![image-2024-12-16-10-48-33-376](https://github.com/user-attachments/assets/25c14b50-e121-43d0-bb0d-21235e855d61)

**Comment by bengaineyarm** [comment]
Hi @sooyeon-kang
Can you run gatord on the target with the `-d` flag, and paste here the output. This should help identify the issue.

Something like:

`gatord -d 2>&1 | tee log.txt`

**Comment by sooyeon-kang** [comment]
It was because of the counter setting. 
I solved it.  I'm sorry.
Thank you.
