### ISSUE TITLE
Compile fail in kernel 4.14

### ISSUE THREAD

**Issue by StephenShiSiyuan** [ARM-software/gator#6]
Hi,

I found there is a compile error on my kernel 4.14 version, as bellow:

kernel/msm-4.14/drivers/gator/gator_events_meminfo.c:253:49: warning: implicit conversion from enumeration type 'enum node_stat_item' to different enumeration type 'enum zone_stat_item' [-Wenum-conversion]
error, forbidden warning: gator_events_meminfo.c:253
kernel/msm-4.14/scripts/Makefile.build:363: recipe for target 'drivers/gator/gator_events_meminfo.o' failed
make[3]: *** [drivers/gator/gator_events_meminfo.o] Error 1

And I didn't find the way to contribute my patch, so I add the patch here, hope it helpful.

[0001-meminfo-use-global_node_page_state-rather-than-globa.txt](https://github.com/ARM-software/gator/files/2584001/0001-meminfo-use-global_node_page_state-rather-than-globa.txt)

**Comment by bengaineyarm** [comment]
Hi Stephen

Thanks for spotting that. I'll apply the appropriate change on our end and upload it with the next release.
